# Project properties & versions
mod_group=com.nzoros.randombutton
mod_id=randombutton
mod_name=Minecraft Random Button
mod_authors=Nzoros10
mod_version=0.1.0-beta.1
mod_description=Press the Random Button to trigger unpredictable events. Includes Lucky and Unlucky Cubes, loot rewards, meteors, and many more events. Beta release.

# The license for your mod - see LICENSE
mod_license=MIT

java_version=21

# The minecraft version used for compiling and testing
minecraft_version=1.21.1

# The neoforge version used for compiling and testing
neoforge_version=21.1.233
# range of allowed NeoForge versions (used in neoforge.mods.toml)
neoforge_version_range=[21.1,)
# range of allowed neo loader versions (used in neoforge.mods.toml)
neo_loader_version_range=[4,)

# check these versions on https://fabricmc.net/develop/
fabric_loader_version=0.19.3
# if you don't need fabric api, you can remove this line as well as the one in fabric/build.gradle.kts
fabric_api_version=0.116.12+1.21.1

# Done to improve gradle performance.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# org.gradle.configuration-cache=true
